### create counter
GET http://localhost:8090/counter/create/

### increment

PATCH http://localhost:8090/counter/11

### get value
GET http://localhost:8090/counter/11

### get all

GET http://localhost:8090/counter